name: Build and Release WPF Project

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      Solution_Name: InverseProblem.sln
      Build_Configuration: Release

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore NuGet Packages
      run: dotnet restore $env:Solution_Name

    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Build_Configuration

    - name: Verify Build Files
      run: |
        $buildPath = "E:\Self hosted runner\actions-runner\_work\InverseProblem\*\bin\$env:Build_Configuration"
        Write-Host "Listing files in the build directory:"
        Get-ChildItem -Path $buildPath -Recurse

    - name: Archive Build Artifacts
      run: |
        mkdir BuildArtifacts
        Copy-Item -Path */bin/${{ matrix.configuration }}/* -Destination BuildArtifacts -Recurse
        Compress-Archive -Path BuildArtifacts/* -DestinationPath BuildArtifacts.zip
      shell: pwsh

    - name: Create GitHub Release Tag
      run: |
        # Формирование тега на основе номера сборки
        $tag_name = "v${{ github.run_number }}"
        echo "Tag name: $tag_name"
        git tag $tag_name
        git push origin $tag_name

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ github.run_number }}"
        files: BuildArtifacts.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: BuildArtifacts.zip
        asset_name: BuildArtifacts.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
