name: Build and Release WPF Project

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      Solution_Name: InverseProblem.sln
      Build_Configuration: Release

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore NuGet Packages
      run: dotnet restore $env:Solution_Name

    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=$env:Build_Configuration

    - name: Archive Build Artifacts
      run: |
        $buildArtifactsFolder = "E:\Self hosted runner\actions-runner\_work\InverseProblem\BuildArtifacts"
        $outputFile = "$buildArtifactsFolder\BuildArtifacts.zip"
        New-Item -ItemType Directory -Force -Path $buildArtifactsFolder
        xcopy */bin/$env:Build_Configuration/* $buildArtifactsFolder /E /I
        Compress-Archive -Path "$buildArtifactsFolder\*" -DestinationPath $outputFile

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: "Build v${{ github.run_number }}"
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}\BuildArtifacts.zip  # Обновлено с использованием переменной GitHub workspace
        asset_name: BuildArtifacts.zip
        asset_content_type: application/zip
